package swaputils

const (
	BCH_ERROR_NET_ID uint8 = iota
	BCH_MAINNET_P2PKH_NET_ID
	BCH_MAINNET_P2SH_NET_ID
	BCH_TESTNET_P2PKH_NET_ID
	BCH_TESTNET_P2SH_NET_ID
	BCH_REGNET_P2PKH_NET_ID
	BCH_REGNET_P2SH_NET_ID
	ETH_NET_ID
)
